name: Go


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: 
  
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with: 
<<<<<<< HEAD
        go-version: 1.22.0
=======
        go-version: 1.18
>>>>>>> 6c1c5e1 (chore: initial configurations are added)

    - name: Build
      run: go build -v ArrayAndString/TwoSum.go
      
    - name: Test
      run: go test -v ArrayAndString/TwoSum.go